-- 1. Create Inquiries Table
CREATE TABLE IF NOT EXISTS inquiries (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    question TEXT NOT NULL
);

-- 2. Create Students Table
CREATE TABLE IF NOT EXISTS students (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    role TEXT NOT NULL, -- Class & Roll (e.g. 'Grade VI - A')
    info TEXT NOT NULL, -- Guardian details
    status TEXT DEFAULT 'Active'
);

-- 3. Create Teachers Table
CREATE TABLE IF NOT EXISTS teachers (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    role TEXT NOT NULL, -- Subject (e.g. 'Mathematics')
    info TEXT NOT NULL, -- Class In-charge details
    status TEXT DEFAULT 'Active'
);

-- 4. Enable Row Level Security (RLS) and allow public/anon Read and Write Access for this demo
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;

-- Create Policies (Select and Insert for everyone)
CREATE POLICY "Allow public select for inquiries" ON inquiries FOR SELECT USING (true);
CREATE POLICY "Allow public insert for inquiries" ON inquiries FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public select for students" ON students FOR SELECT USING (true);
CREATE POLICY "Allow public insert for students" ON students FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public select for teachers" ON teachers FOR SELECT USING (true);
CREATE POLICY "Allow public insert for teachers" ON teachers FOR INSERT WITH CHECK (true);

-- 5. Seed Teachers Data
INSERT INTO teachers (id, name, role, info, status) VALUES
('TCH202601', 'Mr. S.P. Sahu', 'Mathematics', 'In-charge: Grade VI', 'Active'),
('TCH202602', 'Mrs. Rashmi Dewangan', 'Science', 'In-charge: Grade VII', 'Active'),
('TCH202603', 'Mr. R.K. Patel', 'Hindi', 'In-charge: Grade VIII', 'Active'),
('TCH202604', 'Miss Anjali Tiwari', 'English', 'In-charge: Grade IX', 'Active'),
('TCH202605', 'Mr. Vinod Nishad', 'Social Studies', 'In-charge: Grade X', 'Active'),
('TCH202606', 'Mr. S.P. Sahu', 'Science', 'In-charge: Grade VI', 'Active'),
('TCH202607', 'Mrs. Rashmi Dewangan', 'Hindi', 'In-charge: Grade VII', 'Active'),
('TCH202608', 'Mr. R.K. Patel', 'English', 'In-charge: Grade VIII', 'Active'),
('TCH202609', 'Miss Anjali Tiwari', 'Social Studies', 'In-charge: Grade IX', 'Active'),
('TCH202610', 'Mr. Vinod Nishad', 'Mathematics', 'In-charge: Grade X', 'Active'),
('TCH202611', 'Mr. S.P. Sahu', 'Hindi', 'In-charge: Grade VI', 'Active'),
('TCH202612', 'Mrs. Rashmi Dewangan', 'English', 'In-charge: Grade VII', 'Active'),
('TCH202613', 'Mr. R.K. Patel', 'Social Studies', 'In-charge: Grade VIII', 'Active'),
('TCH202614', 'Miss Anjali Tiwari', 'Mathematics', 'In-charge: Grade IX', 'Active'),
('TCH202615', 'Mr. Vinod Nishad', 'Science', 'In-charge: Grade X', 'Active')
ON CONFLICT (id) DO NOTHING;

-- 6. Seed Students Data (50 sample records)
INSERT INTO students (id, name, role, info, status) VALUES
('STU2026001', 'Amit Prasad (101)', 'Grade VI - A', 'Guardian: Sneha Singh Senior', 'Active'),
('STU2026002', 'Rahul Kumar (102)', 'Grade VII - A', 'Guardian: Priya Sharma Senior', 'Active'),
('STU2026003', 'Sneha Singh (103)', 'Grade VIII - A', 'Guardian: Vikram Verma Senior', 'Active'),
('STU2026004', 'Priya Sharma (104)', 'Grade IX - A', 'Guardian: Neha Joshi Senior', 'Active'),
('STU2026005', 'Vikram Verma (105)', 'Grade X - A', 'Guardian: Rohan Gupta Senior', 'Active'),
('STU2026006', 'Neha Joshi (106)', 'Grade VI - A', 'Guardian: Amit Prasad Senior', 'Active'),
('STU2026007', 'Rohan Gupta (107)', 'Grade VII - A', 'Guardian: Rahul Kumar Senior', 'Active'),
('STU2026008', 'Amit Prasad (108)', 'Grade VIII - A', 'Guardian: Sneha Singh Senior', 'Active'),
('STU2026009', 'Rahul Kumar (109)', 'Grade IX - A', 'Guardian: Priya Sharma Senior', 'Active'),
('STU2026010', 'Sneha Singh (110)', 'Grade X - A', 'Guardian: Vikram Verma Senior', 'Active'),
('STU2026011', 'Priya Sharma (111)', 'Grade VI - A', 'Guardian: Neha Joshi Senior', 'Active'),
('STU2026012', 'Vikram Verma (112)', 'Grade VII - A', 'Guardian: Rohan Gupta Senior', 'Active'),
('STU2026013', 'Neha Joshi (113)', 'Grade VIII - A', 'Guardian: Amit Prasad Senior', 'Active'),
('STU2026014', 'Rohan Gupta (114)', 'Grade IX - A', 'Guardian: Rahul Kumar Senior', 'Active'),
('STU2026015', 'Amit Prasad (115)', 'Grade X - A', 'Guardian: Sneha Singh Senior', 'Active'),
('STU2026016', 'Rahul Kumar (116)', 'Grade VI - A', 'Guardian: Priya Sharma Senior', 'Active'),
('STU2026017', 'Sneha Singh (117)', 'Grade VII - A', 'Guardian: Vikram Verma Senior', 'Active'),
('STU2026018', 'Priya Sharma (118)', 'Grade VIII - A', 'Guardian: Neha Joshi Senior', 'Active'),
('STU2026019', 'Vikram Verma (119)', 'Grade IX - A', 'Guardian: Rohan Gupta Senior', 'Active'),
('STU2026020', 'Neha Joshi (120)', 'Grade X - A', 'Guardian: Amit Prasad Senior', 'Active'),
('STU2026021', 'Rohan Gupta (121)', 'Grade VI - A', 'Guardian: Rahul Kumar Senior', 'Active'),
('STU2026022', 'Amit Prasad (122)', 'Grade VII - A', 'Guardian: Sneha Singh Senior', 'Active'),
('STU2026023', 'Rahul Kumar (123)', 'Grade VIII - A', 'Guardian: Priya Sharma Senior', 'Active'),
('STU2026024', 'Sneha Singh (124)', 'Grade IX - A', 'Guardian: Vikram Verma Senior', 'Active'),
('STU2026025', 'Priya Sharma (125)', 'Grade X - A', 'Guardian: Neha Joshi Senior', 'Active'),
('STU2026026', 'Vikram Verma (126)', 'Grade VI - A', 'Guardian: Rohan Gupta Senior', 'Active'),
('STU2026027', 'Neha Joshi (127)', 'Grade VII - A', 'Guardian: Amit Prasad Senior', 'Active'),
('STU2026028', 'Rohan Gupta (128)', 'Grade VIII - A', 'Guardian: Rahul Kumar Senior', 'Active'),
('STU2026029', 'Amit Prasad (129)', 'Grade IX - A', 'Guardian: Sneha Singh Senior', 'Active'),
('STU2026030', 'Rahul Kumar (130)', 'Grade X - A', 'Guardian: Priya Sharma Senior', 'Active'),
('STU2026031', 'Sneha Singh (131)', 'Grade VI - A', 'Guardian: Vikram Verma Senior', 'Active'),
('STU2026032', 'Priya Sharma (132)', 'Grade VII - A', 'Guardian: Neha Joshi Senior', 'Active'),
('STU2026033', 'Vikram Verma (133)', 'Grade VIII - A', 'Guardian: Rohan Gupta Senior', 'Active'),
('STU2026034', 'Neha Joshi (134)', 'Grade IX - A', 'Guardian: Amit Prasad Senior', 'Active'),
('STU2026035', 'Rohan Gupta (135)', 'Grade X - A', 'Guardian: Rahul Kumar Senior', 'Active'),
('STU2026036', 'Amit Prasad (136)', 'Grade VI - A', 'Guardian: Sneha Singh Senior', 'Active'),
('STU2026037', 'Rahul Kumar (137)', 'Grade VII - A', 'Guardian: Priya Sharma Senior', 'Active'),
('STU2026038', 'Sneha Singh (138)', 'Grade VIII - A', 'Guardian: Vikram Verma Senior', 'Active'),
('STU2026039', 'Priya Sharma (139)', 'Grade IX - A', 'Guardian: Neha Joshi Senior', 'Active'),
('STU2026040', 'Vikram Verma (140)', 'Grade X - A', 'Guardian: Rohan Gupta Senior', 'Active'),
('STU2026041', 'Neha Joshi (141)', 'Grade VI - A', 'Guardian: Amit Prasad Senior', 'Active'),
('STU2026042', 'Rohan Gupta (142)', 'Grade VII - A', 'Guardian: Rahul Kumar Senior', 'Active'),
('STU2026043', 'Amit Prasad (143)', 'Grade VIII - A', 'Guardian: Sneha Singh Senior', 'Active'),
('STU2026044', 'Rahul Kumar (144)', 'Grade IX - A', 'Guardian: Priya Sharma Senior', 'Active'),
('STU2026045', 'Sneha Singh (145)', 'Grade X - A', 'Guardian: Vikram Verma Senior', 'Active'),
('STU2026046', 'Priya Sharma (146)', 'Grade VI - A', 'Guardian: Neha Joshi Senior', 'Active'),
('STU2026047', 'Vikram Verma (147)', 'Grade VII - A', 'Guardian: Rohan Gupta Senior', 'Active'),
('STU2026048', 'Neha Joshi (148)', 'Grade VIII - A', 'Guardian: Amit Prasad Senior', 'Active'),
('STU2026049', 'Rohan Gupta (149)', 'Grade IX - A', 'Guardian: Rahul Kumar Senior', 'Active'),
('STU2026050', 'Amit Prasad (150)', 'Grade X - A', 'Guardian: Sneha Singh Senior', 'Active')
ON CONFLICT (id) DO NOTHING;
